### ISSUE TITLE
Just to say thanks, and also you can use console.group tidy things up.

### ISSUE THREAD

**Issue by FateRiddle** [jefflombard/use-reducer-logger#6]
I was trying to do something similar(a logger for my own state management hooks), and your code works perfectly, thanks.
Recommend adding `console.group` `console.groupEnd` to group things up, just like redux-logger.

**Comment by jefflombard** [comment]
@FateRiddle Thanks for the note! 

I'll leave this open if anyone gets to it before me. Good example of it here:
https://github.com/LogRocket/redux-logger/blob/master/src/core.js
